sonar.host.url=https://sonarcloud.io

sonar.sources=system-1/src,system-2/src,system-3/src
sonar.tests=system-1/tests,system-2/tests,system-3/test
sonar.javascript.lcov.reportPaths=system-1/coverage/lcov.info,system-2/coverage/lcov.info,system-3/coverage/lcov.info
sonar.coverage.exclusions=**/tests/**,**/test/**,**/*.test.*,**/*.spec.*
sonar.exclusions=**/node_modules/**,**/.next/**,**/build/**,**/coverage/**
