-- Run this on the AUTH database (same one customers table lives in)

-- 1. Add is_admin column to customers
ALTER TABLE customers ADD COLUMN IF NOT EXISTS is_admin BOOLEAN NOT NULL DEFAULT false;

-- 2. Create the admin account
-- Password: admin123456  (bcrypt hash with 10 rounds, generated by auth-service bcrypt)
INSERT INTO customers (full_name, email, phone, birthday, gender, password, is_admin)
VALUES (
  'Admin',
  'admin@gmail.com',
  '+639000000000',
  '1990-01-01',
  'Other',
  '$2b$10$P8alCRtqR.7/ZNlsmJFOoO5q4deV94MUMNHfGSLv/OSTaMYbkZafu',
  true
)
ON CONFLICT (email) DO UPDATE
  SET is_admin = true,
      password  = '$2b$10$P8alCRtqR.7/ZNlsmJFOoO5q4deV94MUMNHfGSLv/OSTaMYbkZafu';

-- 3. Create oos_settings table for OOS configuration
CREATE TABLE IF NOT EXISTS oos_settings (
  key   TEXT PRIMARY KEY,
  value TEXT,
  updated_at TIMESTAMPTZ DEFAULT now()
);

INSERT INTO oos_settings (key, value) VALUES
  ('delivery_fee',        '50'),
  ('free_delivery_min',   '500'),
  ('min_order_amount',    '100'),
  ('max_order_items',     '20'),
  ('oos_enabled',         'true'),
  ('order_cutoff_time',   '21:00'),
  ('contact_email',       'support@pharmaquick.com'),
  ('contact_phone',       '+63 900 000 0000')
ON CONFLICT (key) DO NOTHING;
