-- Run this SQL in the Supabase SQL Editor for the primary project.
-- Creates the branches table used by the backend /api/branches endpoint.

CREATE TABLE IF NOT EXISTS branches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  address TEXT NOT NULL,
  phone TEXT,
  latitude NUMERIC(10, 7) NOT NULL,
  longitude NUMERIC(10, 7) NOT NULL,
  opening_time TIME NOT NULL,
  closing_time TIME NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS branches_is_active_idx
  ON branches (is_active);

ALTER TABLE branches
ADD COLUMN IF NOT EXISTS latitude NUMERIC(10, 7);

ALTER TABLE branches
ADD COLUMN IF NOT EXISTS longitude NUMERIC(10, 7);

INSERT INTO branches (
  id,
  name,
  address,
  phone,
  latitude,
  longitude,
  opening_time,
  closing_time,
  is_active
)
VALUES
  (
    1,
    'Branch 1',
    'Ayala Avenue, Makati City, Metro Manila',
    '09171234567',
    14.5547299,
    121.0244452,
    '08:00:00',
    '20:00:00',
    TRUE
  ),
  (
    2,
    'Branch 2',
    'Ortigas Center, Pasig City, Metro Manila',
    '09181234567',
    14.5869164,
    121.0607074,
    '09:00:00',
    '21:00:00',
    TRUE
  ),
  (
    3,
    'Branch 3',
    'Quezon Avenue, Quezon City, Metro Manila',
    '09191234567',
    14.6395146,
    121.0336707,
    '08:30:00',
    '19:30:00',
    TRUE
  )
ON CONFLICT (id) DO UPDATE
SET
  name = EXCLUDED.name,
  address = EXCLUDED.address,
  phone = EXCLUDED.phone,
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude,
  opening_time = EXCLUDED.opening_time,
  closing_time = EXCLUDED.closing_time,
  is_active = EXCLUDED.is_active;

SELECT setval(
  pg_get_serial_sequence('branches', 'id'),
  COALESCE((SELECT MAX(id) FROM branches), 1),
  true
);

-- If the table already exists and you only deleted the id column,
-- run this instead of recreating the whole table:
--
-- ALTER TABLE branches
-- ADD COLUMN IF NOT EXISTS latitude NUMERIC(10, 7);
--
-- ALTER TABLE branches
-- ADD COLUMN IF NOT EXISTS longitude NUMERIC(10, 7);
--
-- ALTER TABLE branches
-- ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;
--
-- ALTER TABLE branches
-- ADD CONSTRAINT branches_pkey PRIMARY KEY (id);
